version: '3.8'

services:
  web-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - CONFIG_PATH=/root/config
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/root/config

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: webanalyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data: